name: PR Validation
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get changed directories
        id: dirs
        uses: tj-actions/changed-files@v35
        with:
          dir_names: 'true'
      - name: Install dependencies
        run: |
          cd validation && npm install --registry=https://npm.lisk.com/
      - name: Run Validation scripts
        run: |
          cd validation && npm run start -- ${{ steps.dirs.outputs.all_changed_and_modified_files }}
